version: '3.7'
services:
    newspluse:
      build: .
      restart: always
      volumes:
        - ./:/usr/src/app
      ports:
        - 8080:80
      expose:
        - 80
      command: "gunicorn --chdir /usr/src/app --access-logfile - --error-logfile - --bind 8080:80 newspluse.wsgi:application"