# Generated by Django 5.2.5 on 2025-08-27 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='social_media_icons',
            new_name='SocialMediaIcon',
        ),
    ]
