# Generated by Django 5.2.3 on 2025-06-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='images',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='media',
        ),
    ]
