"""
Django settings for newspluse project.

Generated by 'django-admin startproject' using Django 5.2.5.
"""

import os
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from decouple import config
from openai import OpenAI

# =========================
# BASE DIR
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# SECURITY
# =========================
SECRET_KEY = config('MY_SECRET_KEY')
DEBUG = True

MAIN_DOMAIN = config('MAIN_DOMAIN')
ALLOWED_HOSTS = ["*"]

CORS_ORIGIN_WHITELIST = ["*"]

CSRF_TRUSTED_ORIGINS = [
    f"{MAIN_DOMAIN}"
]


# =========================
# API KEYS
# =========================
OPENROUTER_API_KEY = os.getenv(
    "OPENROUTER_API_KEY",
    "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"
)
YOUTUBE_API_KEY = config("YOUTUBE_API_KEY")
FB_ACCESS_TOKEN = config("FB_ACCESS_TOKEN")


# =========================
# APPS
# =========================
INSTALLED_APPS = [
    "accounts",
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "main_core",
    "contact",
]


# =========================
# MIDDLEWARE
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",   # لازم يكون بعد SecurityMiddleware
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.BrokenLinkEmailsMiddleware",  # اختياري
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URLS & WSGI
# =========================
ROOT_URLCONF = 'newspluse.urls'
WSGI_APPLICATION = 'newspluse.wsgi.application'

# =========================
# TEMPLATES
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# =========================
# DATABASE
# =========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =========================
# PASSWORD VALIDATORS
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# =========================
# INTERNATIONALIZATION
# =========================
LANGUAGES = [
    ("en", "English"),
    ("ar", "Arabic"),
]

LANGUAGE_CODE = "en"
USE_I18N = True
USE_L10N = True
USE_TZ = True

LOCALE_PATHS = [
    BASE_DIR / "locale",
]




# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/




# =========================
# STATIC & MEDIA FILES
# =========================
STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",   # فولدر static الأساسي
]
STATIC_ROOT = BASE_DIR / "staticfiles"   # الملفات بعد collectstatic

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# =========================
# DEFAULT PRIMARY KEY
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# =========================
# JAZZMIN SETTINGS
# =========================
JAZZMIN_SETTINGS = {
    "site_title": "MohaMed",
    "site_header": "MohaMed",
    "site_brand": "MohaMed",
    "site_logo": "/Logo_site/logosite.png",
    "login_logo": "",
    "login_logo_dark": "",
    "site_logo_classes": "img-circle",
    "site_icon": "/Logo_site/logosite.png",
    "welcome_sign": "Welcome to the library",
    "copyright": "Acme Library Ltd",
    "search_model": ["auth.User", "auth.Group"],
    "user_avatar": "profile.profile_picture.url",

    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.User"},
        {"app": "books"},
    ],

    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],

    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],

    "custom_links": {
        "books": [{
            "name": "Make Messages",
            "url": "make_messages",
            "icon": "fas fa-comments",
            "permissions": ["books.view_book"]
        }]
    },

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "custom_css": "admin/css/main.css",
    "custom_js": "admin/js/main.js"
}



# """
# Django settings for newspluse project.

# Generated by 'django-admin startproject' using Django 5.2.5.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# import os
# from pathlib import Path
# from django.utils.translation import gettext_lazy as _
# import gettext
# from decouple import config
# from openai import OpenAI
  
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = config('MY_SECRET_KEY')
# OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "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")
# YOUTUBE_API_KEY = config('YOUTUBE_API_KEY')
# FB_ACCESS_TOKEN = config('FB_ACCESS_TOKEN')

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
# MAIN_DOMAIN = config('MAIN_DOMAIN')

# ALLOWED_HOSTS = ['*']
# CORS_ORIGIN_WHITELIST = ['*']
# CSRF_TRUSTED_ORIGINS = [
#     f"{MAIN_DOMAIN}"
# ]



# # Application definition

# INSTALLED_APPS = [
#     'accounts',
#     'jazzmin',
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'main_core',
#     'contact',
# ]

# # MIDDLEWARE = [
# #     'django.middleware.locale.LocaleMiddleware',
# #     'django.middleware.security.SecurityMiddleware',
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.BrokenLinkEmailsMiddleware',  # Optional: for broken link notifications
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# #     'django.middleware.common.CommonMiddleware',

# # ]
# MIDDLEWARE = [
#     "django.middleware.security.SecurityMiddleware",
#     "whitenoise.middleware.WhiteNoiseMiddleware",  # لازم يكون بعد SecurityMiddleware
#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.locale.LocaleMiddleware",
#     "django.middleware.common.BrokenLinkEmailsMiddleware",  # اختياري
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# ROOT_URLCONF = 'newspluse.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, "templates")],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'newspluse.wsgi.application'



# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/


# # Django settings.py snippet for language support
# LANGUAGES = [
#     ('en', 'English'),
#     ('ar', 'Arabic'),
# ]
# LANGUAGE_CODE = 'en'
# USE_I18N = True
# USE_L10N = True
# USE_TZ = True
# LOCALE_PATHS = [
#     # Add your locale path here
#     os.path.join(BASE_DIR, 'locale'),
# ]




# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# # STATIC_URL = '/static/'

# # STATICFILES_DIRS = [
# #     BASE_DIR / "static",
# #     "/usr/src/app/static/",
# # ]
# # MEDIA_URL = '/media/'
# # MEDIA_ROOT = os.path.join(BASE_DIR,'media')


# # BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
# # STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  


# BASE_DIR = Path(__file__).resolve().parent.parent

# STATIC_URL = '/static/'

# STATICFILES_DIRS = [
#     BASE_DIR / "static",   # ده فولدر static الأساسي بتاعك
# ]

# STATIC_ROOT = BASE_DIR / "staticfiles"   # هنا هيتجمعوا الملفات بعد collectstatic

# MEDIA_URL = '/media/'
# MEDIA_ROOT = BASE_DIR / "media"


# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# # Jazzmin settings
# JAZZMIN_SETTINGS = {
#     "site_title": "MohaMed",
#     "site_header": "MohaMed",
#     "site_brand": "MohaMed",
#     "site_logo": "/Logo_site/logosite.png",
#     # "login_logo": "/Logo_site/logosite.png",
#     # "login_logo_dark": "/Logo_site/logosite.png",
#     "login_logo": "",
#     "login_logo_dark": "",

#     "site_logo_classes": "img-circle",
#     "site_icon": "/Logo_site/logosite.png",
#     "welcome_sign": "Welcome to the library",
#     "copyright": "Acme Library Ltd",
#     "search_model": ["auth.User", "auth.Group"],
#     "user_avatar": "profile.profile_picture.url",
#     "topmenu_links": [
#         {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
#         {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
#         {"model": "auth.User"},
#         {"app": "books"},
#     ],
#     "usermenu_links": [
#         {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
#         {"model": "auth.user"}
#     ],
#     "show_sidebar": True,
#     "navigation_expanded": True,
#     "hide_apps": [],
#     "hide_models": [],
#     "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
#     "custom_links": {
#         "books": [{
#             "name": "Make Messages",
#             "url": "make_messages",
#             "icon": "fas fa-comments",
#             "permissions": ["books.view_book"]
#         }]
#     },
#     "icons": {
#         "auth": "fas fa-users-cog",
#         "auth.user": "fas fa-user",
#         "auth.Group": "fas fa-users",
#     },
#     "default_icon_parents": "fas fa-chevron-circle-right",
#     "default_icon_children": "fas fa-circle",
#     "related_modal_active": False,
#     "custom_css": None,
#     "custom_js": None,
#     "use_google_fonts_cdn": True,
#     "show_ui_builder": False,
#     "changeform_format": "horizontal_tabs",
#     "changeform_format_overrides": {"auth.user": "collapsible", "auth.group": "vertical_tabs"},
#     "language_chooser": True,
# }

# JAZZMIN_UI_TWEAKS = {
#     "theme": "darkly",
#     # "theme": "simplex",
#     "dark_mode_theme": "darkly",
#     "custom_css": "admin/css/main.css",
#     "custom_js": "admin/js/main.js"
# }