# Generated by Django 5.2.5 on 2025-08-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_breaking',
            field=models.BooleanField(default=False),
        ),
    ]
