# Generated by Django 5.2.5 on 2025-08-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0002_newsarticle_is_breaking'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlickrPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='flickr_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flickr Photo',
                'verbose_name_plural': 'Flickr Photos',
            },
        ),
    ]
