# Generated by Django 5.2.5 on 2025-08-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0003_flickrphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
