# Generated by Django 5.2.5 on 2025-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_core', '0004_newsarticle_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
